questions:
  # 日志配置
  - variable: application.logLevel
    label: "日志级别"
    description: |
      日志详细程度
    type: enum
    options:
      - info
      - warning
      - debug
      - error
    default: info
    group: "基础配置"

  - variable: application.logFormat
    label: "日志格式"
    description: |
      日志输出格式，可选 json-pretty、json、plain
    type: enum
    options:
      - json-pretty
      - json
      - plain
    default: json-pretty
    group: "基础配置"

  # 功能特性
  - variable: application.features.automaticUnchangedApproval
    label: "自动批准未变更镜像"
    description: |
      镜像未变时自动通过
    type: boolean
    default: false
    group: "功能特性"

  - variable: application.features.automaticChildApproval
    label: "自动批准子资源"
    description: |
      例：Deployment 自动创建的 Pod
    type: boolean
    default: true
    group: "功能特性"

  - variable: application.features.detectionMode
    label: "只警告不拒绝"
    description: |
      如开启，所有校验失败仅产生警告，不拒绝
    type: boolean
    default: false
    group: "功能特性"

  - variable: application.features.namespacedValidation.mode
    label: "命名空间校验模式"
    description: |
      只在指定命名空间或全部命名空间校验，ignore=全部放行
    type: enum
    options:
      - ignore
      - validate
    default: ignore
    group: "功能特性"

  - variable: application.features.resourceValidationMode
    label: "资源校验范围"
    description: |
      选择校验所有资源还是仅校验Pod（all/podsOnly）
    type: enum
    options:
      - all
      - podsOnly
    default: all
    group: "功能特性"

  - variable: application.features.cache.expirySeconds
    label: "签名校验缓存时长(秒)"
    description: |
      签名校验结果最大缓存时间（秒）
    type: int
    default: 30
    group: "功能特性"

  - variable: application.features.cache.cacheErrors
    label: "缓存校验失败"
    description: |
      签名校验失败结果是否也缓存
    type: boolean
    default: true
    group: "功能特性"

  # 策略规则
  - variable: application.policy
    label: "策略规则"
    description: |
      按 YAML 数组格式填写。
      每项格式：
        - pattern: 镜像匹配模式，通配符支持，如 *:*；
        - validator: 对应下方校验器名称；
        - with: (可选) 校验可选参数。如 trustRoot 指定信任根。
      示例（可直接编辑）：

      - pattern: "*:*"
        validator: deny
      - pattern: "docker.io/library/*:*"
        validator: dockerhub
      - pattern: "docker.io/securesystemsengineering/*:*"
        validator: dockerhub
        with:
          trustRoot: sse
      - pattern: "registry.k8s.io/*:*"
        validator: allow

    type: multiline
    default: |-
      - pattern: "*:*"
        validator: deny
      - pattern: "docker.io/library/*:*"
        validator: dockerhub
      - pattern: "docker.io/securesystemsengineering/*:*"
        validator: dockerhub
        with:
          trustRoot: sse
      - pattern: "registry.k8s.io/*:*"
        validator: allow
    required: true
    group: "策略规则"

  # 校验器
  - variable: application.validators
    label: "校验器"
    description: |
      按 YAML 数组格式填写。
      每项格式：
        - name: 校验器名称（与策略规则 validator 字段一致）；
        - type: 校验类型（如 static/notaryv1）；
        - approve: 是否自动通过（static类型才有）；
        - trustRoots: (可选) 支持Notaryv1等类型的公钥数组，每项包含 name、key。
      示例（可直接编辑）：

      - name: allow
        type: static
        approve: true
      - name: deny
        type: static
        approve: false
      - name: dockerhub
        type: notaryv1
        trustRoots:
          - name: default
            key: |
              -----BEGIN PUBLIC KEY-----
              MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEOXYta5TgdCwXTCnLU09W5T4M4r9f
              QQrqJuADP6U7g5r9ICgPSmZuRHP/1AYUfOQW3baveKsT969EfELKj1lfCA==
              -----END PUBLIC KEY-----
          - name: sse
            key: |
              -----BEGIN PUBLIC KEY-----
              MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEsx28WV7BsQfnHF1kZmpdCTTLJaWe
              d0CA+JOi8H4REuBaWSZ5zPDe468WuOJ6f71E7WFg3CVEVYHuoZt2UYbN/Q==
              -----END PUBLIC KEY-----
    type: multiline
    default: |-
      - name: allow
        type: static
        approve: true
      - name: deny
        type: static
        approve: false
      - name: dockerhub
        type: notaryv1
        trustRoots:
          - name: default
            key: |
              -----BEGIN PUBLIC KEY-----
              MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEOXYta5TgdCwXTCnLU09W5T4M4r9f
              QQrqJuADP6U7g5r9ICgPSmZuRHP/1AYUfOQW3baveKsT969EfELKj1lfCA==
              -----END PUBLIC KEY-----
          - name: sse
            key: |
              -----BEGIN PUBLIC KEY-----
              MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEsx28WV7BsQfnHF1kZmpdCTTLJaWe
              d0CA+JOi8H4REuBaWSZ5zPDe468WuOJ6f71E7WFg3CVEVYHuoZt2UYbN/Q==
              -----END PUBLIC KEY-----
    required: true
    group: "校验器"
