{{ $root := . -}}
{{ range .Values.application.validators -}}
{{ if and (hasKey . "auth") (and (hasKey .auth "username") (hasKey .auth "password") (or (eq .type "notaryv1") (hasKey .auth "registry"))) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-auth
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "connaisseur.labels" $root | nindent 4 }}
type: Opaque
data:
  secret.yaml: {{ .auth | toYaml | b64enc }}
---
{{- end }}
{{- end }}
