apiVersion: v1
kind: Service
metadata:
  name: {{ include "connaisseur.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "connaisseur.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kubernetes.service.type }}
  ports:
    - port: {{ .Values.kubernetes.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "connaisseur.selectorLabels" . | nindent 4 }}
