apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "connaisseur.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "connaisseur.labels" . | nindent 4 }}
  {{- if .Values.kubernetes.serviceaccount.annotations }}
  annotations:
    {{- toYaml .Values.kubernetes.serviceaccount.annotations | nindent 4 }}
  {{- end }}
